language: java

jdk:
  - openjdk7
  - oraclejdk7

android:
 components:
    - build-tools-16.1.0

    # The SDK version used to compile the project
    - android-16

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-16

before_install:
  - chmod +x gradlew
  - cp -R /usr/local/android-sdk-23.0.2 ./android-sdk

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew build # check

branches:
  only:
    - develop
    - master

install: /bin/true

addons:
  apt_packages:
    - swig
