language: java

jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - chmod +x gradlew

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check

branches:
  only:
    - develop
    - master