language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
  - chmod +x gradlew

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew build # check

branches:
  only:
    - develop
    - master

install: /bin/true

addons:
  apt_packages:
    - swig
