language : android

jdk: oraclejdk7

env:
  global:
    # - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - ANDROID_HOME=C://Users/hwa/AppData/Local/Android/sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}

android:
 components:
    - build-tools-16.1.0

    # The SDK version used to compile the project
    - android-16

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-16

before_install:
  - chmod +x gradlew

install:
  - true

script: ./gradlew assembleDebug