language : android
sudo: true
jdk: oraclejdk7

android:
 components:
    - build-tools-23.0.1

    # The SDK version used to compile the project
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: musiczoa@naver.com

addons:
  apt_packages:
    - swig

before_install:
  #- chmod +x gradlew
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - echo "sdk.dir=$ANDROID_HOME" > travisci.properties
  - echo "ndk.dir=$ANDROID_NDK_HOME" >> travisci.properties
  - echo "swig.path=`which swig`" >> travisci.properties
  - echo "ndk.debug=true" >> travisci.properties
  - cat travisci.properties

script: ./gradlew build

# assembleDebug, build -> Success. debug -> Fail